### ISSUE TITLE
Rogue Console Log

### ISSUE THREAD

**Issue by blackjack26** [stytchauth/stytch-node#111]
I couldn't for the life of me find out where in my code I was logging something to the console, until I realized that every update request I made to a user was logged in your code.

Is it possible to remove this `console.log`?

https://github.com/stytchauth/stytch-node/blob/1fb7e359c8fbd95692b354dbf4521907d8584368/lib/users.ts#L357

**Comment by cal-stytch** [comment]
@blackjack26 this should be resolved in the newest release of the package (v3.11.2)
