### ISSUE TITLE
how can i test stytch node using mocha?

### ISSUE THREAD

**Issue by chaudhryjunaid** [stytchauth/stytch-node#163]
Is there any documentation related to stubbing stytch node for unit testing with mocha?

**Comment by jeremy-stytch** [comment]
Hi @chaudhryjunaid, thanks for the question!

Mocha recommends a few libraries in their wiki under [Mocks, Stubs, & Spies](https://github.com/mochajs/mocha/wiki#mocks-stubs--spies).

Depending on what you want to test, you may want a spy, fake, stub, mock, or other [Sinon helpers](https://sinonjs.org/releases/v14/).

Here's an example that uses a [Sinon spy](https://sinonjs.org/releases/v14/spies/) so the request continues through to the real Stytch Test environment:

```javascript
const sinon = require("sinon");
const assert = require("assert");

const stytch = require("stytch");

const client = new stytch.Client({
  project_id: process.env["STYTCH_PROJECT_ID"],
  secret: process.env["STYTCH_SECRET"],
  env: stytch.envs.test,
});

describe("Magic Links", () => {
  describe("with a Sinon stub", () => {
    it("should record the request parameters", async () => {
      const spy = sinon.spy(client.magicLinks, "authenticate");

      // Reserved in Stytch Test for testing
      const testSuccessToken = "DOYoip3rvIMMW5lgItikFK-Ak1CfMsgjuiCyI7uuU94=";

      await client.magicLinks.authenticate(testSuccessToken);

      // https://sinonjs.org/releases/v14/spies/#api
      assert(spy.calledOnceWithExactly(testSuccessToken));
    });
  });
});
```

**Comment by jeremy-stytch** [comment]
Oh, I forgot to close this yesterday. I'll do that now.

@chaudhryjunaid, let us know if this helped you! If you have more questions, please open another issue or join us in [Slack](https://join.slack.com/t/stytch/shared_invite/zt-nil4wo92-jApJ9Cl32cJbEd9esKkvyg).
