### ISSUE TITLE
Typing not working for moduleResolution nodenext

### ISSUE THREAD

**Issue by jhwz** [stytchauth/stytch-node#174]
When importing `stytch` using `nodenext` typescript isn't able to find the typings.

```
Could not find a declaration file for module 'stytch'. 'stytch/module.mjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/stytch` if it exists or add a new declaration (.d.ts) file containing `declare module 'stytch';`ts(7016)
```

You should just need to add the `"types"` field to your exports in `package.json`:

```json
  "exports": {
    "require": "./dist/index.js",
    "import": "./dist/index.mjs",
    "types": "./types/lib/index.d.ts"
  },
```

Ideally, more types would be exported (`User`, `Session`, etc) like #118 mentions but that can be worked around.

**Comment by max-stytch** [comment]
@jhwz thank you for bearing with us - we have reworked our type exports and [all types](https://github.com/stytchauth/stytch-node/blob/main/lib/b2c/index.ts#L1C1-L15) should be publicly exposed now with the **7.0.0** release
