### ISSUE TITLE
AbortController is not a constructor

### ISSUE THREAD

**Issue by benwyrosdick** [stytchauth/stytch-node#175]
When running stytch in node `v18.12.1` I get the following error when I call `stytchClient.oauth.authenticate`:

```
{
  err: RequestError: AbortController is not a constructor
      at request (/home/ben/projects/enveloop-api/node_modules/stytch/dist/shared.js:37:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async validateAuthToken (/home/ben/projects/enveloop-api/lib/auth.js:191:57) {
    request: { method: 'POST', url: 'oauth/authenticate', data: [Object] }
  },
  opts: {}
}
```

it works fine in node `v17.1.0`

**Comment by benwyrosdick** [comment]
as a note it works if I change the import of `isomorphic-unfetch` to `node-fetch` and use it's `fetch` method instead inside of the stytch library

**Comment by benwyrosdick** [comment]
tested in `5.12.1` and `5.17.0`

**Comment by beama3** [comment]
I don't know what this means

**Comment by max-stytch** [comment]
Heya @benwyrosdick we no longer use `isomorphic-unfetch` internally as of #255. We now use the native `fetch` builtin. I'm going to close this issue for now - if anything else pops up please feel free to reopen!

**Comment by benwyrosdick** [comment]
Thank you for the feedback.
