### ISSUE TITLE
The docs for deleting TOTPs are incorrect

### ISSUE THREAD

**Issue by PorterK** [stytchauth/stytch-node#179]
The docs here: https://stytch.com/docs/api/delete-user-totp are incorrect - if you change the language to node it says the function should live at `client.totps.deleteTOTP` but it is really `client.users.deleteTOTP`

I think the first one makes more sense semantically but the 2nd one makes the most sense based on the documentation (why is deleting TOTPs in the users section? You don't even provide it any user information)

My suggestion would be to move the various `delete` methods into the proper part of the documentation & into the proper sections of the client code.

In the mean time just making the documentation accurate would be awesome!

Is there a spot where the public can PR into the documentation? I would be happy to move these to the semantically correct sections in the code & docs

**Comment by nicole-stytch** [comment]
👋 thanks for flagging this! We'll update our docs to include the correct method (`client.users.deleteTOTP`). We don't allow public PRs for our docs at the moment, but I appreciate the offer!

I definitely see your point about making this endpoint live under `client.totps`, but our current pattern is to group all auth factor deletion endpoints under `client.users`. There are some factors (such as email address) that don't feat as neatly under product categories. We'll keep this in mind during future refactors, though!

Thanks again for the report.
