### ISSUE TITLE
6.0 Release breaks middleware in NextJS

### ISSUE THREAD

**Issue by dsbrianwebster** [stytchauth/stytch-node#191]
We had a nice implementation of Stytch in NextJS middleware that appears to be breaking after the update to version 6.

<img width="554" alt="image" src="https://user-images.githubusercontent.com/8154653/219692611-ea89e5bb-4f48-49dc-938b-149828e01b1a.png">

<img width="658" alt="Screenshot 2023-02-17 at 10 09 30 AM" src="https://user-images.githubusercontent.com/8154653/219692164-e17b51d3-98a5-4b3b-94a4-7da18b72c6e4.png">

<img width="455" alt="Screenshot 2023-02-17 at 10 14 14 AM" src="https://user-images.githubusercontent.com/8154653/219692796-9dbfa169-a4f0-40a8-8300-1641f798a259.png">

Reverting back to version 5 fixes the issue for now.

**Comment by max-stytch** [comment]
Hey @dsbrianwebster - I suspect this is an issue with #185 - we'll take a look

**Comment by max-stytch** [comment]
Hey @dsbrianwebster we've released [v6.0.1](https://www.npmjs.com/package/stytch/v/6.0.1) - can you confirm whether that fixes the issue on your end?

**Comment by dsbrianwebster** [comment]
Confirmed @max-stytch! Thank you for your help on this, and thank you for Stytch!
