### ISSUE TITLE
Can't import Stytch in NextJS with TypeScript

### ISSUE THREAD

**Issue by stevemc4** [stytchauth/stytch-node#43]
Hello, I was trying to using Stytch for my side projects. But apparently the library can't be imported in NextJS with TypeScript. The error shows as the picture below:

![image](https://user-images.githubusercontent.com/20576341/125669300-72306033-d685-4fa1-babd-36b622d7ccf3.png)

The script I used is below:
```ts
import { NextApiRequest, NextApiResponse } from 'next'
import * as stytch from 'stytch'

export default async (req: NextApiRequest, res: NextApiResponse): Promise<void> => {
  const projectId = process.env.STYTCH_PROJECT_ID
  const secret = process.env.STYTCH_PROJECT_SECRET
  if (!projectId && !secret) {
    res.status(500).json({
      status: 500,
      error: 'Internal Server Error'
    })
  } else {
    const client = new stytch.Client({
      project_id: projectId ?? '',
      secret: secret ?? '',
      env: stytch.envs.test
    })

    const response = await client.otps.whatsapp.loginOrCreate({
      phone_number: req.body.phone,
      create_user_as_pending: true
    })

    res.status(200).json(response)
  }
}
```

Thank you!

**Comment by jeremy-stytch** [comment]
Thanks for the report! I apologize for not noticing this issue sooner (I'm enabling repo notifications for myself now).

This should be fixed now that #44 is released in [v3.0.2](https://github.com/stytchauth/stytch-node/releases/tag/v3.0.2). Feel free to re-open this issue if that didn't fix it.
