### ISSUE TITLE
Stytch is still using test environment even after stytch.envs.live

### ISSUE THREAD

**Issue by lerichardson** [stytchauth/stytch-node#45]
My authentication app is still using the test environment, as shown by the URL in the magic links I get:
![image](https://user-images.githubusercontent.com/72626657/127753137-3bea1b2d-e154-4b7e-97c3-7db89322e1fd.png)
even though my code uses `stytch.envs.live`.  
Is this an issue with my code? I'm using the live API keys, as shown by my code:
```js
const client = new stytch.Client({
    project_id: "project-live-",
    secret: "secret-live-",
    env: stytch.envs.live
  }
);
```
What is wrong?

**Comment by jeremy-stytch** [comment]
Hi, thanks for filing this issue! I'm assuming that the self-close means you've solved it. In case we can improve the library or documentation (or just to to help future searchers), was was the resolution?
